import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalProvider from "@/components/ModalProvider";
import AuthorModal from "@/components/modals/AuthorModal";
import PostModal from "@/components/modals/PostModal";
import { Navbar } from "@/components/Navbar";
import ToasterProvider from "@/components/ToasterProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <Navbar/>
        <AuthorModal/>
        <PostModal/>
        {children}
      </body>
    </html>
  );
}
